name: Docker Build and Push for releases

on:
  release:
    types: [ published, edited ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # get the tag of the release, e.g. 1.2.3
    - name: Get tag
      id: get_tag
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        
    - name: Build and push the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PW: ${{ secrets.DOCKER_PW }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de  
        docker build -f docker-images/eth-netstats/Dockerfile -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/eth-netstats:${{ steps.get_tag.outputs.tag }} .
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/eth-netstats:${{ steps.get_tag.outputs.tag }} 
        docker build -f docker-images/fast-geth/Dockerfile -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/fast-geth:${{ steps.get_tag.outputs.tag }} .
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/fast-geth:${{ steps.get_tag.outputs.tag }}
        docker build -f docker-images/las2peer/Dockerfile -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/las2peer:${{ steps.get_tag.outputs.tag }} .
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/las2peer:${{ steps.get_tag.outputs.tag }}
        docker build -f docker-images/monitored-geth-client/Dockerfile -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/monitored-geth-client:${{ steps.get_tag.outputs.tag }} .
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/monitored-geth-client:${{ steps.get_tag.outputs.tag }}
